export const AUTOMATION_ID = {
    download: (entity: string) => `${entity}-download-button`,
    login: () => `login-download-button`,
    filterActivator: (entity: string) => `${entity}-filter-activator-button`,
    add: (entity: string) => `${entity}-add-button`,
    edit: (entity: string) => `${entity}-edit-button`,
    delete: (entity: string) => `${entity}-delete-button`,
    removePair: (entity: string) => `${entity}-remove-pair-button`,
    addPair: (entity: string) => `${entity}-add-pair-button`,
    deleteConfirm: (entity: string) => `${entity}-delete-confirm-button`,
    deleteCancel: (entity: string) => `${entity}-delete-cancel-button`,
    translationsConfirm: (entity: string) => `${entity}-translations-confirm-button`,
    translationsCancel: (entity: string) => `${entity}-translations-cancel-button`,
    formConfirm: (entity: string) => `${entity}-form-confirm-button`,
    formCancel: (entity: string) => `${entity}-form-cancel-button`,
    formInput: (entity: string, inputName: string) => `${entity}-${inputName}-form-input-field`,
    formNumberInput: (entity: string, inputName: string) =>
        `${entity}-${inputName}-form-number-input-field`,
    formSelect: (entity: string, inputName: string) => `${entity}-${inputName}-form-select-field`,
    formSwitch: (entity: string, inputName: string) => `${entity}-${inputName}-form-switch-field`,
    formTranslationActivator: (entity: string) => `${entity}-form-translation-activator-button`,
    paginationPrev: (entity: string) => `${entity}-pagination-prev-button`,
    paginationNext: (entity: string) => `${entity}-pagination-next-button`,
    paginationPage: (entity: string, page: number) => `${entity}-pagination-page-${page}`,
    navigationItem: (key: string) => `${key}-navigation-item`,
    navigationGroup: (key: string) => `${key}-navigation-group`,
} as const;
