export type NavigationKey =
    | "navigation.login"
    | "navigation.location"
    | "navigation.airports"
    | "navigation.countries"
    | "navigation.cities"
    | "navigation.functions"
    | "navigation.flows"
    | "navigation.areas"
    | "navigation.flowRules"
    | "navigation.systemSettings"
    | "navigation.locales"
    | "navigation.geographicTypes"
    | "navigation.currencies"
    | "navigation.marketGroups";
